server:
  port: 24110
spring:
  application:
    name: publisher
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:distcomp}?currentSchema=${DB_SCHEMA:public}
    username: ${DB_USER:postgres}
    password: ${DB_PASS:postgres}
    driver-class-name: org.postgresql.Driver
  liquibase:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
springdoc:
  api-docs.path: "/public/swagger/v3/api-docs"
  swagger-ui.path: "/public/swagger/swagger-ui.html"
  swagger-ui:
    doc-expansion: none
discussion:
  url: http://localhost:24130